#! /usr/bin/env bash

# Run regular maintenance jobs in host's crontab after 'sf up' has been started
# PHY: crontab -l | grep -v cronjob | echo "15 0 * * sun /sf/sfbin/cronjob all >/dev/shm/sf/run/logs/cronjob.out 2>/dev/shm/sf/run/logs/cronjob.err" | crontab -

SF_BASEDIR="/sf"
SF_DATADIR="${SF_BASEDIR}/data"
SF_MV_EXIT_FN="${SF_DATADIR}/share/relay-exit-nodes-mullvad.txt"
SF_MV_RELAY_FN="${SF_DATADIR}/share/proxies.txt"
SF_HA_CONF="${SF_DATADIR}/share/haproxy-1040.conf"
SF_TOR_EXIT_FN="${SF_DATADIR}/share/tor-exit-nodes.txt"

[ "$PATH" != *"sbin" ] && PATH=/usr/sbin:/usr/local/sbin:$PATH

# SF_GLOBAL_EXIT_FN="/sf/config/etc/relay-exit-nodes-global.txt" # Provided by Blind Mouse
# aka curl -H "Auth: hAV2fDFN..." http://92.x.x.x:50613 >/sf/config/etc/relay-exit-nodes-global.txt

mk_haproxy1040_conf() {
    local fn="$(mktemp)"

    [[ -z $fn ]] && return

    cat >"${fn}"<<-'EOF'
defaults
  timeout connect 15s
  timeout client 10s
  timeout server 60s

frontend socks-in
  mode tcp
  bind :1080
  default_backend socks-out

backend socks-out
  mode tcp
  default-server check observe layer4 error-limit 3 on-error mark-down inter 3600s downinter 60s rise 1
EOF
    shuf <"${SF_MV_RELAY_FN}" | while read -r str; do
        ips="$(dig +short "${str%:*}" | grep -v ^';;')" || continue
        [[ -z $ips ]] && continue
        echo "  server s${n} ${ips}:${str##*:} #$str"
        ((n++))
    done >>"${fn}"
    mv "${fn}" "${SF_HA_CONF}"
}

# Make a list of working proxies
# and exit mullvad proxy IPs.
mk_mullvad_relays()
{
    local IFS
    local str
    local arr
    local ip
    local ips
    local proxies

    docker exec sf-mullvad true 2>/dev/null || { echo >&2 "sf-mullvad not running. Execute this after ${CDC}sfbin/sf${CN} up"; return; }

    IFS=""
    str=$(curl -fsSL --retry 3 --max-time 15 https://api.mullvad.net/www/relays/all/ 2>/dev/null | jq -r '.[] |  select(.socks_name != null) | select(.socks_port != null)  | "\(.socks_name):\(.socks_port)"' |grep -v ^-)
    str=${str//[^a-z0-9-:.$'\n']}
    [[ -z $str ]] && return

    IFS=$'\n'
    arr=($str)
    for h in "${arr[@]}"; do
        echo -n "Testing $h - "
        ip=$(docker exec sf-mullvad bash -c "curl --retry 1 --max-time 5 -fsSL -x 'socks5://$h'  ipinfo.io" | jq -r '.ip | select(. != null)')
        ip=${ip//[^a-f0-9:.]}
        [[ -z $ip ]] && { echo "SKIP"; continue; }
        echo "$ip"
        ips+="$ip"$'\n'
        proxies+="$h"$'\n'
    done
    echo -n "$proxies" >"${SF_MV_RELAY_FN}"
    echo -n "$ips" >"${SF_MV_EXIT_FN}"
    mk_haproxy1040_conf
}

mk_tor_relays()
{
    local IFS
    local str
    IFS=""
    str=$(curl -SsfL --retry 3 --max-time 15 'https://www.dan.me.uk/torlist/?exit')
    [[ -z $str ]] && return
    echo -n "$str" >"${SF_TOR_EXIT_FN}"
}

mk_global_relays()
{
    local IFS
    local str

    echo "NOT YET IMPLEMENTED. We are using a private list from Blind Mouse"
    # IFS=""
    # str=${str//[^a-z0-9-.$'\n']}
    # [[ -z $str ]] && return

    # echo "$str" >"${SF_GLOBAL_EXIT_FN}"
}

mk_geolite() {
    local fn="GeoLite2-City.mmdb"
    [ ! -f "${SF_BASEDIR:-/sf}/config/.env" ] && return
    eval "$(grep ^MAX "${SF_BASEDIR:-/sf}/config/.env")"
    [ -z "$MAXMIND_KEY" ] && return

    curl -fL "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${MAXMIND_KEY:-KEY-NOT-SET}&suffix=tar.gz" | tar xfvz  - --strip-components=1  --no-anchored -C '/tmp' "${fn}" || return
    rm -f "${SF_DATADIR}/share/${fn}"
    chmod 644 "/tmp/${fn}"
    mv "/tmp/${fn}" "${SF_DATADIR}/share/${fn}"
}

str="$*"
[[ $str == *all* ]] && {
    mk_geolite
    str="mullvad tor global"
}

[[ $str == *mullvad* ]] && { mk_mullvad_relays; is_ran=1; }
[[ $str == *tor* ]] && { mk_tor_relays; is_ran=1; }
# [[ $str == *global* ]] && { mk_global_relays; is_ran=1; }

source "${SF_BASEDIR:?}/sfbin/funcs_admin.sh" >/dev/null
source "${SF_BASEDIR:-/sf}/config/etc/sf/timers.conf" 2>/dev/null
lgpurge "${SF_TIMEOUT_IDLE_DAYS}" "${SF_TIMEOUT_NAUGHTY_DAY}"

fn="/dev/shm/sf/run/logs/segfault.log"
[ -f "$fn" ] && :>"${fn:?}"

[[ -n $is_ran ]] && exit

echo "Usage: $0 [mullvad, tor, all]"
